dataset:
  dataset_size: 1024
  dequantize: 0.0
  do_round: false
  load_data: true
  max_node_num: 10
  name: lobster_10_10_4k
dev: !!python/object/apply:torch.device
- cpu
exp_dir: mc_gnn
exp_name: lobster_10_20_4k
folder_name: mc_gnn_lobster_10_10_4k__Feb-03-23-41-07_11736
mcmc:
  eps:
  - 0.1
  fixed_node_number: true
  grad_step_size:
  - 0.005
  name: langevin
  step_num: 1000
  use_mh: false
model:
  models:
    model_1:
      channel_num_list:
      - 2
      - 4
      - 4
      - 4
      - 2
      dropout_p: 0.0
      feature_nums:
      - 16
      - 16
      - 16
      - 16
      - 16
      gnn_hidden_num_list:
      - 16
      - 16
      - 16
      - 16
      name: gin
      use_norm_layers: false
  name: mc_gnn
  stack_num: 1
model_save_dir: mc_gnn/lobster_10_20_4k/mc_gnn_lobster_10_10_4k__Feb-03-23-41-07_11736/models
permute: true
run_id: '11736'
sample:
  batch_size: 128
save_dir: mc_gnn/lobster_10_20_4k/mc_gnn_lobster_10_10_4k__Feb-03-23-41-07_11736
seed: 1234
test:
  batch_size: 128
  split: 0.3
train:
  batch_size: 32
  fixed_noise: false
  lr_dacey: 0.99
  lr_init: 0.001
  max_epoch: 501
  momentum: 0.9
  sample_interval: 500
  save_interval: 100
  shuffle: true
  sigmas:
  - 0.1
  - 0.2
  - 0.4
  - 0.6
  - 0.8
  - 1.6
  weight_decay: 0.0
